version: '3'

services:

  myapp:
    image: raihansh/nextapp:01
    container_name: myapp
    ports:
      - "3000:3000"
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus-alerts.yaml:/etc/prometheus/prometheus-alerts.yaml
    ports:
      - "9090:9090"
    depends_on:
      - myapp

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
