apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app # This label is used by the Service and Prometheus to find this Pod.
    spec:
      containers:
      - name: my-app-container
        image: raihansh/nextapp:01
        ports:
        - containerPort: 3000
      - name: nginx-sidecar
        image: nginx:latest
        ports:
        - containerPort: 80 # Nginx port exposed to the service.
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
