apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'my-app'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: my-app
        - source_labels: [__address__]
          action: replace
          target_label: __address__
          regex: ([^:]+):(?:\d+)
          replacement: ${1}:3000
        metrics_path: /api/metrics

      # NEW: This job scrapes cluster-level metrics from kube-state-metrics.
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']