apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'my-app'
        metrics_path: /api/metrics # The path Nginx will proxy
        static_configs:
          # This now works because the service points to Nginx (port 80)
          # and Nginx knows how to handle the /api/metrics path.
          - targets: ['{{ .Release.Name }}-my-app-service:80']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['{{ .Release.Name }}-kube-state-metrics:8080']