apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-app-service
  labels:
    app: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80