apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
spec:
  type: ClusterIP
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-service
spec:
  type: LoadBalancer
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000