apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitoring-deployment
  labels:
    app: monitoring
spec:
  replicas: {{ .Values.monitoring.replicaCount }}
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      serviceAccountName: {{ .Release.Name }}-monitoring
      containers:
      - name: prometheus
        image: "{{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}"
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      - name: grafana
        image: "{{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}"
        ports:
        - containerPort: 3000
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: {{ .Release.Name }}-prometheus-config