apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;

      # This rule passes general traffic to your app
      location / {
        proxy_pass http://localhost:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      # NEW: This rule ensures Prometheus can access the metrics endpoint
      location /api/metrics {
        proxy_pass http://localhost:80/api/metrics;
      }
    }