apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'my-app'
        metrics_path: /api/metrics
        static_configs:
          - targets: ['{{ .Release.Name }}-my-app-service:3000'] # <--- Changed port from 80 to 3000

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['{{ .Release.Name }}-kube-state-metrics:8080']