app:
  replicaCount: 1
  image:
    repository: raihansh/nextapp
    tag: "01"

monitoring:
  replicaCount: 1
  prometheus:
    image:
      repository: prom/prometheus
      tag: latest
  grafana:
    image:
      repository: grafana/grafana
      tag: latest

kubeStateMetrics:
  replicaCount: 1
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.10.1